services:
  mongodb:
    image: mongo:5.0
    ports: 
      - "127.0.0.1:27017:27017"
      
  web:
    build: ./web-app
    ports:
      - "3000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017

  

