services:
  webapp:
    build: ./web-app
    ports:
      - "5000:5000"
    links:
      - my_mongodb
    depends_on:
      - my_mongodb

  my_mongodb:
    image: mongo:5.0
    hostname: my_mongodb
    ports: 
      - "27017:27017"
