name: Machine Learning Client Build & Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.7", "3.9", "3.11"]
    defaults:
      run:
        working-directory: machine-learning-client
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install --user pipenv
          pip3 install -r requirements.txt
      - name: 'Create .env File'
        run: |
          touch .env
          echo AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} >> .env
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
          echo MONGO_DBNAME=${{ secrets.MONGO_DBNAME }} >> .env
        working-directory: ./machine-learning-client
      - name: Test with pytest
        run: |
          python3 -m pytest
